jobs:
  build:
    defaults:
      run:
        working-directory: ./oauth-angular20-example
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: ./oauth-angular20-example/package-lock.json
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
name: Node.js CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
